---
- name: Check user on PostgreSQL
  hosts: debian
  become: yes
  gather_facts: yes

  vars_files:
    - ./group_vars/vars.yml

  tasks:
    - name: Run SELECT 1 on remote PostgreSQL
      shell: |
        PGPASSWORD={{ db_password }} psql -U {{ db_user }} -h {{ ip_host }} -c "SELECT 1"
      register: db_check
      failed_when: db_check.rc != 0

    - name: Show PostgreSQL query output
      debug:
        var: db_check.stdout