---
- name: Install PostgreSQL 14 on Debian
  hosts: debian
  become: yes
  gather_facts: yes

  vars_files:
    - ./group_vars/vars.yml

  pre_tasks:
    - name: Install gnupg for managing keys
      apt:
        name: gnupg
        state: present

    - name: Add PostgreSQL APT repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL APT repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_facts.lsb.codename }}-pgdg main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Install PostgreSQL 14 on Debian (statistically)
      apt:
        name: postgresql-14=14.*
        state: present
        allow_unauthenticated: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install python3-packaging via apt
      apt:
        name: python3-packaging
        state: present

    - name: Install psycopg2 (PostgreSQL Python adapter) via apt
      apt:
        name: python3-psycopg2
        state: present

    - name: Find out if PostgreSQL is initialized
      stat:
        path: /var/lib/postgresql/14/main/pg_hba.conf
      register: postgres_data

    - name: Check if PostgreSQL 14 main cluster exists
      shell: "pg_lsclusters | grep -w '14\\s\\+main'"
      register: cluster_check
      failed_when: false
      changed_when: false

    - name: Initialize PostgreSQL 14 cluster if not exists
      command: "pg_createcluster 14 main --start"
      when: cluster_check.rc != 0

    - name: Allow PostgreSQL to accept external connections
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        regexp: '^#listen_addresses'
        line: "listen_addresses = '*'"
      notify:
        - restart postgresql
    
    - name: Allow user '{{ db_user }}' to connect only from the second server's IP
      lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        line: "host    all    {{ db_user }}    {{ ip_student }}/32    md5"
        insertafter: EOF
      notify:
        - restart postgresql
    
    - name: Start PostgreSQL 14 main cluster directly
      command: "pg_ctlcluster 14 main start"
      ignore_errors: yes
      notify: pg_ctlcluster 14 main restart
