---
- name: Install PostgreSQL 14 on CentOS
  hosts: centos
  become: yes
  gather_facts: yes

  vars_files:
    - ./group_vars/vars.yml

  pre_tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - sudo
        state: present

    - name: Add PostgreSQL 14 repository
      yum_repository:
        name: pgdg14
        description: "PostgreSQL 14 YUM repository"
        baseurl: https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-$releasever-$basearch
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

    - name: Disable built-in PostgreSQL module
      command: dnf -qy module disable postgresql

  tasks:
    - name: Install PostgreSQL 14 server and client
      yum:
        name:
          - postgresql14
          - postgresql14-server
          - postgresql14-contrib
          - python3-psycopg2
        state: present

    - name: Initialize PostgreSQL 14 database
      command: /usr/pgsql-14/bin/postgresql-14-setup initdb
      args:
        creates: /var/lib/pgsql/14/data/PG_VERSION

    - name: Enable PostgreSQL systemd unit
      systemd:
        name: postgresql-14
        enabled: yes

    - name: Ensure PostgreSQL listens on all addresses
      lineinfile:
        path: /var/lib/pgsql/14/data/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"
        state: present
      notify: restart postgresql

    - name: Ensure PostgreSQL is using port 5432
      lineinfile:
        path: /var/lib/pgsql/14/data/postgresql.conf
        regexp: '^#?port\s*='
        line: "port = 5432"
      notify: restart postgresql

    - name: Allow remote connection from student
      lineinfile:
        path: /var/lib/pgsql/14/data/pg_hba.conf
        line: "host    all    {{ db_user }}    {{ ip_student }}/32    md5"
        insertafter: EOF
        state: present
      notify: restart postgresql

    - name: Start PostgreSQL via systemd
      systemd:
        name: postgresql-14
        state: started

    - name: Create PostgreSQL user '{{ db_user }}'
      become_user: postgres
      shell: |
        psql -h 127.0.0.1 -p 5432 -U postgres -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}'" | grep -q 1 || \
        psql -h 127.0.0.1 -p 5432 -U postgres -c "CREATE ROLE {{ db_user }} WITH LOGIN PASSWORD '{{ db_password }}';"
      args:
        executable: /bin/bash

  handlers:
    - name: restart postgresql
      systemd:
        name: postgresql-14
        state: restarted